

export const GET_SINGLE_SCORE = "GET_SINGLE_SCORE";
export const GET_SINGLE_SCORE_SUCCESS = 'GET_SINGLE_SCORE_SUCCESS';
export const GET_SINGLE_SCORE_FAILED = 'GET_SINGLE_SCORE_FAILED';

export const EDIT_SCORE = "EDIT_SCORE";
export const EDIT_SCORE_SUCCESS = 'EDIT_SCORE_SUCCESS';
export const EDIT_SCORE_FAILED = 'EDIT_SCORE_FAILED';
