export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILED = 'CREATE_DEPARTMENT_FAILED';

export const GET_GROUP_LIST = "GET_GROUP_LIST";
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_LIST_FAILED = 'GET_GROUP_LIST_FAILED';

export const GET_SINGLE_GROUP = "GET_SINGLE_GROUP";
export const GET_SINGLE_GROUP_SUCCESS = 'GET_SINGLE_GROUP_SUCCESS';
export const GET_SINGLE_GROUP_FAILED = 'GET_SINGLE_GROUP_FAILED';

export const EDIT_GROUP = "EDIT_GROUP";
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
export const EDIT_GROUP_FAILED = 'EDIT_DEPARTMENT_FAILED';


export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILED = 'DELETE_GROUP_FAILED';