export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const CREATE_DEPARTMENT_FAILED = 'CREATE_DEPARTMENT_FAILED';

export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_FAILED = 'GET_DEPARTMENT_LIST_FAILED';

export const GET_SINGLE_DEPARTMENT = "GET_SINGLE_DEPARTMENT";
export const GET_SINGLE_DEPARTMENT_SUCCESS = 'GET_SINGLE_DEPARTMENT_SUCCESS';
export const GET_SINGLE_DEPARTMENT_FAILED = 'GET_SINGLE_DEPARTMENT_FAILED';

export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const EDIT_DEPARTMENT_SUCCESS = 'EDIT_DEPARTMENT_SUCCESS';
export const EDIT_DEPARTMENT_FAILED = 'EDIT_DEPARTMENT_FAILED';


export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILED = 'DELETE_DEPARTMENT_FAILED';