export const GET_EVENT_LIST = "GET_EVENT_LIST";
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_FAILED = 'GET_EVENT_LIST_FAILED';

export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT";
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
export const GET_SINGLE_EVENT_FAILED = 'GET_SINGLE_EVENT_FAILED';

export const CREATE_EVENT = "CREATE_EVENT_FAILED";
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_FAILED_SUCCESS';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';

export const EDIT_EVENT = "EDIT_EVENT";
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED';

export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED';