export const CREATE_ROLE = "CREATE_ROLE";
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILED = 'CREATE_ROLE_FAILED';

export const GET_ROLE_LIST = "GET_ROLE_LIST";
export const GET_ROLE_LIST_SUCCESS = 'GET_ROLE_LIST_SUCCESS';
export const GET_ROLE_LIST_FAILED = 'GET_ROLE_LIST_FAILED';

export const GET_SINGLE_ROLE = "GET_SINGLE_ROLE";
export const GET_SINGLE_ROLE_SUCCESS = 'GET_SINGLE_ROLE_SUCCESS';
export const GET_SINGLE_ROLE_FAILED = 'GET_SINGLE_ROLE_FAILED';

export const EDIT_ROLE = "EDIT_ROLE";
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_FAILED = 'EDIT_ROLE_FAILED';

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILED = 'DELETE_ROLE_FAILED';