export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILED = 'GET_USER_LIST_FAILED';


export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS';
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED';


export const SUSPEND_USER = "SUSPEND_USER_FAILED";
export const SUSPEND_USER_SUCCESS = 'SUSPEND_USER_FAILED_SUCCESS';
export const SUSPEND_USER_FAILED = 'SUSPEND_USER_FAILED';


export const GET_UNAPROVE_USER_LIST = "GET_UNAPROVE_USER_LIST";
export const GET_UNAPROVE_USER_LIST_SUCCESS = 'GET_UNAPROVE_USER_LIST_SUCCESS';
export const GET_UNAPROVE_USER_LIST_FAILED = 'GET_UNAPROVE_USER_LIST_FAILED';

export const APPROVE_USER = "APPROVE_USER";
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_FAILED = 'APPROVE_USER_FAILED';

export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_FAILED = 'ACTIVATE_USER_FAILED';

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';