export const CREATE_CONTENT = "CREATE_CONTENT";
export const CREATE_CONTENT_SUCCESS = 'CREATE_CONTENT_SUCCESS';
export const CREATE_CONTENT_FAILED = 'CREATE_CONTENT_FAILED';

export const GET_CONTENT_LIST = "GET_CONTENT_LIST";
export const GET_CONTENT_LIST_SUCCESS = 'GET_CONTENT_LIST_SUCCESS';
export const GET_CONTENT_LIST_FAILED = 'GET_CONTENT_LIST_FAILED';

export const GET_SINGLE_CONTENT = "GET_SINGLE_CONTENT";
export const GET_SINGLE_CONTENT_SUCCESS = 'GET_SINGLE_CONTENT_SUCCESS';
export const GET_SINGLE_CONTENT_FAILED = 'GET_SINGLE_CONTENT_FAILED';

export const EDIT_CONTENT = "EDIT_CONTENT";
export const EDIT_CONTENT_SUCCESS = 'EDIT_CONTENT_SUCCESS';
export const EDIT_CONTENT_FAILED = 'EDIT_CONTENT_FAILED';

export const DELETE_CONTENT = "DELETE_CONTENT";
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_FAILED = 'DELETE_ABSENTEE_FAILED';