export const CREATE_BROADCAST = "CREATE_BROADCAST";
export const CREATE_BROADCAST_SUCCESS = 'CREATE_BROADCAST_SUCCESS';
export const CREATE_BROADCAST_FAILED = 'CREATE_BROADCAST_FAILED';

export const GET_BROADCAST_LIST = "GET_BROADCAST_LIST";
export const GET_BROADCAST_LIST_SUCCESS = 'GET_BROADCAST_LIST_SUCCESS';
export const GET_BROADCAST_LIST_FAILED = 'GET_BROADCAST_LIST_FAILED';


export const GET_SINGLE_BROADCAST = "GET_SINGLE_BROADCAST";
export const GET_SINGLE_BROADCAST_SUCCESS = 'GET_SINGLE_BROADCAST_SUCCESS';
export const GET_SINGLE_BROADCAST_FAILED = 'GET_SINGLE_BROADCAST_FAILED';

export const EDIT_BROADCAST = "EDIT_BROADCAST";
export const EDIT_BROADCAST_SUCCESS = 'EDIT_BROADCAST_SUCCESS';
export const EDIT_BROADCAST_FAILED = 'EDIT_BROADCAST_FAILED';


export const DELETE_BROADCAST = "DELETE_BROADCAST";
export const DELETE_BROADCAST_SUCCESS = 'DELETE_BROADCAST_SUCCESS';
export const DELETE_BROADCAST_FAILED = 'DELETE_BROADCAST_FAILED';