
export const GET_REQUEST_LIST = "GET_REQUEST_LIST";
export const GET_REQUEST_LIST_SUCCESS = 'GET_REQUEST_LIST_SUCCESS';
export const GET_REQUEST_LIST_FAILED = 'GET_REQUEST_LIST_FAILED';

export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST";
export const GET_SINGLE_REQUEST_SUCCESS = 'GET_SINGLE_REQUEST_SUCCESS';
export const GET_SINGLE_REQUEST_FAILED = 'GET_SINGLE_REQUEST_FAILED';

export const EDIT_REQUEST = "EDIT_REQUEST";
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';
export const EDIT_REQUEST_FAILED = 'EDIT_REQUEST_FAILED';

export const CLOSE_INCIDENT = "CLOSE_INCIDENT";
export const CLOSE_INCIDENT_SUCCESS = 'CLOSE_INCIDENT_SUCCESS';
export const CLOSE_INCIDENT_FAILED = 'CLOSE_INCIDENT_FAILED';

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAILED = 'DELETE_REQUEST_FAILED';