export const GET_SICKNESS_LIST = "GET_SICKNESS_LIST";
export const GET_SICKNESS_LIST_SUCCESS = 'GET_SICKNESS_LIST_SUCCESS';
export const GET_SICKNESS_LIST_FAILED = 'GET_SICKNESS_LIST_FAILED';

export const GET_SINGLE_SICKNESS = "GET_SINGLE_SICKNESS";
export const GET_SINGLE_SICKNESS_SUCCESS = 'GET_SINGLE_SICKNESS_SUCCESS';
export const GET_SINGLE_SICKNESS_FAILED = 'GET_SINGLE_SICKNESS_FAILED';

export const CLOSE_SICKNESS = "CLOSE_SICKNESS";
export const CLOSE_SICKNESS_SUCCESS = 'CLOSE_SICKNESS_SUCCESS';
export const CLOSE_SICKNESS_FAILED = 'CLOSE_SICKNESS_FAILED';

export const DELETE_SICKNESS = "DELETE_SICKNESS";
export const DELETE_SICKNESS_SUCCESS = 'DELETE_SICKNESS_SUCCESS';
export const DELETE_SICKNESS_FAILED = 'DELETE_SICKNESS_FAILED';