export const CREATE_CAMPUS = "CREATE_CAMPUS";
export const CREATE_CAMPUS_SUCCESS = 'CREATE_CAMPUS_SUCCESS';
export const CREATE_CAMPUS_FAILED = 'CREATE_CAMPUS_FAILED';

export const GET_CAMPUS_LIST = "GET_CAMPUS_LIST";
export const GET_CAMPUS_LIST_SUCCESS = 'GET_CAMPUS_LIST_SUCCESS';
export const GET_CAMPUS_LIST_FAILED = 'GET_CAMPUS_LIST_FAILED';


export const GET_SINGLE_CAMPUS = "GET_SINGLE_CAMPUS";
export const GET_SINGLE_CAMPUS_SUCCESS = 'GET_SINGLE_CAMPUS_SUCCESS';
export const GET_SINGLE_CAMPUS_FAILED = 'GET_SINGLE_CAMPUS_FAILED';

export const EDIT_CAMPUS = "EDIT_CAMPUS";
export const EDIT_CAMPUS_SUCCESS = 'EDIT_CAMPUS_SUCCESS';
export const EDIT_CAMPUS_FAILED = 'EDIT_CAMPUS_FAILED';


export const DELETE_CAMPUS = "DELETE_CAMPUS";
export const DELETE_CAMPUS_SUCCESS = 'DELETE_CAMPUS_SUCCESS';
export const DELETE_CAMPUS_FAILED = 'DELETE_CAMPUS_FAILED';