export const GET_QUALITY_ASSURANCE_LIST = "GET_QUALITY_ASSURANCE_LIST";
export const GET_QUALITY_ASSURANCE_LIST_SUCCESS = 'GET_QUALITY_ASSURANCE_LIST_SUCCESS';
export const GET_QUALITY_ASSURANCE_LIST_FAILED = 'GET_QUALITY_ASSURANCE_LIST_FAILED';

export const GET_SINGLE_QUALITY_ASSURANCE = "GET_SINGLE_QUALITY_ASSURANCE";
export const GET_SINGLE_QUALITY_ASSURANCE_SUCCESS = 'GET_SINGLE_QUALITY_ASSURANCE_SUCCESS';
export const GET_SINGLE_QUALITY_ASSURANCE_FAILED = 'GET_SINGLE_QUALITY_ASSURANCE_FAILED';

export const CLOSE_QUALITY_ASSURANCE = "CLOSE_QUALITY_ASSURANCE";
export const CLOSE_QUALITY_ASSURANCE_SUCCESS = 'CLOSE_QUALITY_ASSURANCE_SUCCESS';
export const CLOSE_QUALITY_ASSURANCE_FAILED = 'CLOSE_QUALITY_ASSURANCE_FAILED';

export const DELETE_QUALITY_ASSURANCE = "DELETE_QUALITY_ASSURANCE";
export const DELETE_QUALITY_ASSURANCE_SUCCESS = 'DELETE_QUALITY_ASSURANCE_SUCCESS';
export const DELETE_QUALITY_ASSURANCE_FAILED = 'DELETE_QUALITY_ASSURANCE_FAILED';