export const GET_CONFLICT_LIST = "GET_CONFLICT_LIST";
export const GET_CONFLICT_LIST_SUCCESS = 'GET_CONFLICT_LIST_SUCCESS';
export const GET_CONFLICT_LIST_FAILED = 'GET_CONFLICT_LIST_FAILED';

export const GET_SINGLE_CONFLICT = "GET_SINGLE_CONFLICT";
export const GET_SINGLE_CONFLICT_SUCCESS = 'GET_SINGLE_CONFLICT_SUCCESS';
export const GET_SINGLE_CONFLICT_FAILED = 'GET_SINGLE_CONFLICT_FAILED';

export const CLOSE_CONFLICT = "CLOSE_CONFLICT";
export const CLOSE_CONFLICT_SUCCESS = 'CLOSE_CONFLICT_SUCCESS';
export const CLOSE_CONFLICT_FAILED = 'CLOSE_CONFLICT_FAILED';

export const DELETE_CONFLICT = "DELETE_CONFLICT";
export const DELETE_CONFLICT_SUCCESS = 'DELETE_CONFLICT_SUCCESS';
export const DELETE_CONFLICT_FAILED = 'DELETE_CONFLICT_FAILED';