export const CREATE_ABSENTEE = "CREATE_ABSENTEE";
export const CREATE_ABSENTEE_SUCCESS = 'CREATE_ABSENTEE_SUCCESS';
export const CREATE_ABSENTEE_FAILED = 'CREATE_ABSENTEE_FAILED';

export const GET_ABSENTEE_LIST = "GET_ABSENTEE_LIST";
export const GET_ABSENTEE_LIST_SUCCESS = 'GET_ABSENTEE_LIST_SUCCESS';
export const GET_ABSENTEE_LIST_FAILED = 'GET_ABSENTEE_LIST_FAILED';


export const GET_SINGLE_ABSENTEE = "GET_SINGLE_ABSENTEE";
export const GET_SINGLE_ABSENTEE_SUCCESS = 'GET_SINGLE_ABSENTEE_SUCCESS';
export const GET_SINGLE_ABSENTEE_FAILED = 'GET_SINGLE_ABSENTEE_FAILED';

export const EDIT_ABSENTEE = "EDIT_ABSENTEE";
export const EDIT_ABSENTEE_SUCCESS = 'EDIT_ABSENTEE_SUCCESS';
export const EDIT_ABSENTEE_FAILED = 'EDIT_ABSENTEE_FAILED';

export const CLOSE_INCIDENT = "CLOSE_INCIDENT";
export const CLOSE_INCIDENT_SUCCESS = 'CLOSE_INCIDENT_SUCCESS';
export const CLOSE_INCIDENT_FAILED = 'CLOSE_INCIDENT_FAILED';

export const DELETE_ABSENTEE = "DELETE_ABSENTEE";
export const DELETE_ABSENTEE_SUCCESS = 'DELETE_ABSENTEE_SUCCESS';
export const DELETE_ABSENTEE_FAILED = 'DELETE_ABSENTEE_FAILED';